package System;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author leyla
 */
public class AndraTaBortPersonal extends javax.swing.JFrame {
    private InfDB idb;
    
    /**
     * Creates new form AndraTaBortPersonal
     */
    public AndraTaBortPersonal(InfDB idb) {
        initComponents();
        this.idb=idb;
        fyllPersonalEpost();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        pnlRedigeraPersonal4 = new javax.swing.JPanel();
        lblPersonalFornamn4 = new javax.swing.JLabel();
        txtRedigeraPersonalEpost4 = new javax.swing.JTextField();
        lblPersonalLosenord4 = new javax.swing.JLabel();
        btnRedigeraPersonal4 = new javax.swing.JButton();
        lblPersonalEpost4 = new javax.swing.JLabel();
        lblRedigeraPersonalMeddelande4 = new javax.swing.JLabel();
        lblRedigeraPersonalValj4 = new javax.swing.JLabel();
        txtRedigeraPersonalFornamn4 = new javax.swing.JTextField();
        txtRedigeraPersonalEfternamn4 = new javax.swing.JTextField();
        lblPersonalEfternamn4 = new javax.swing.JLabel();
        cbRedigeraPersonal4 = new javax.swing.JComboBox<>();
        lblRedigeraPersonal4 = new javax.swing.JLabel();
        pwdRedigeraPersonalLosenord4 = new javax.swing.JPasswordField();
        pnlTaBortPersonal = new javax.swing.JPanel();
        cbTaBortPersonal = new javax.swing.JComboBox<>();
        lblTaBortEnPersonal = new javax.swing.JLabel();
        lblTaBortPersonalMeddelande = new javax.swing.JLabel();
        btnTaBortPersonal = new javax.swing.JButton();
        lblTaBortPersonal = new javax.swing.JLabel();
        lblTaBortPersonalEpost = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRedigeraPersonal4.setBackground(new java.awt.Color(255, 255, 255));

        lblPersonalFornamn4.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonalFornamn4.setText("Förnamn:");

        txtRedigeraPersonalEpost4.setBackground(new java.awt.Color(153, 153, 153));
        txtRedigeraPersonalEpost4.setForeground(new java.awt.Color(0, 0, 0));

        lblPersonalLosenord4.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonalLosenord4.setText("Lösenord:");

        btnRedigeraPersonal4.setBackground(new java.awt.Color(0, 102, 153));
        btnRedigeraPersonal4.setForeground(new java.awt.Color(255, 255, 255));
        btnRedigeraPersonal4.setText("Redigera kund");
        btnRedigeraPersonal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraPersonal4ActionPerformed(evt);
            }
        });

        lblPersonalEpost4.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonalEpost4.setText("Nytt epost:");

        lblRedigeraPersonalMeddelande4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRedigeraPersonalMeddelande4.setForeground(new java.awt.Color(0, 0, 0));

        lblRedigeraPersonalValj4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRedigeraPersonalValj4.setForeground(new java.awt.Color(102, 102, 102));
        lblRedigeraPersonalValj4.setText("Välj epost för personal som ska redigeras:");

        txtRedigeraPersonalFornamn4.setBackground(new java.awt.Color(153, 153, 153));
        txtRedigeraPersonalFornamn4.setForeground(new java.awt.Color(0, 0, 0));
        txtRedigeraPersonalFornamn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRedigeraPersonalFornamn4ActionPerformed(evt);
            }
        });

        txtRedigeraPersonalEfternamn4.setBackground(new java.awt.Color(153, 153, 153));
        txtRedigeraPersonalEfternamn4.setForeground(new java.awt.Color(0, 0, 0));

        lblPersonalEfternamn4.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonalEfternamn4.setText("Efternamn:");

        cbRedigeraPersonal4.setForeground(new java.awt.Color(0, 0, 0));

        lblRedigeraPersonal4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRedigeraPersonal4.setForeground(new java.awt.Color(102, 102, 102));
        lblRedigeraPersonal4.setText("Redigera personal");

        pwdRedigeraPersonalLosenord4.setBackground(new java.awt.Color(153, 153, 153));
        pwdRedigeraPersonalLosenord4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdRedigeraPersonalLosenord4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRedigeraPersonal4Layout = new javax.swing.GroupLayout(pnlRedigeraPersonal4);
        pnlRedigeraPersonal4.setLayout(pnlRedigeraPersonal4Layout);
        pnlRedigeraPersonal4Layout.setHorizontalGroup(
            pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedigeraPersonal4Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRedigeraPersonal4Layout.createSequentialGroup()
                        .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRedigeraPersonal4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addComponent(lblRedigeraPersonalValj4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlRedigeraPersonal4Layout.createSequentialGroup()
                                .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRedigeraPersonalMeddelande4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRedigeraPersonal4Layout.createSequentialGroup()
                                        .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPersonalFornamn4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPersonalEfternamn4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPersonalLosenord4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPersonalEpost4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(81, 81, 81)))
                        .addGap(133, 133, 133))
                    .addGroup(pnlRedigeraPersonal4Layout.createSequentialGroup()
                        .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRedigeraPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRedigeraPersonalFornamn4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbRedigeraPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRedigeraPersonalEfternamn4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pwdRedigeraPersonalLosenord4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlRedigeraPersonal4Layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addComponent(txtRedigeraPersonalEpost4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlRedigeraPersonal4Layout.setVerticalGroup(
            pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedigeraPersonal4Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblRedigeraPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblRedigeraPersonalValj4)
                .addGap(18, 18, 18)
                .addComponent(cbRedigeraPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalFornamn4)
                    .addComponent(txtRedigeraPersonalFornamn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalEfternamn4)
                    .addComponent(txtRedigeraPersonalEfternamn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalLosenord4)
                    .addComponent(pwdRedigeraPersonalLosenord4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlRedigeraPersonal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalEpost4)
                    .addComponent(txtRedigeraPersonalEpost4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRedigeraPersonal4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRedigeraPersonalMeddelande4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Redigera personal", pnlRedigeraPersonal4);

        pnlTaBortPersonal.setBackground(new java.awt.Color(255, 255, 255));

        lblTaBortEnPersonal.setBackground(new java.awt.Color(51, 51, 51));
        lblTaBortEnPersonal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTaBortEnPersonal.setForeground(new java.awt.Color(102, 102, 102));
        lblTaBortEnPersonal.setText("Ta bort personal");

        lblTaBortPersonalMeddelande.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTaBortPersonalMeddelande.setForeground(new java.awt.Color(0, 0, 0));

        btnTaBortPersonal.setBackground(new java.awt.Color(0, 102, 153));
        btnTaBortPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaBortPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnTaBortPersonal.setText("Ta bort personal");
        btnTaBortPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortPersonalActionPerformed(evt);
            }
        });

        lblTaBortPersonal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTaBortPersonal.setForeground(new java.awt.Color(102, 102, 102));
        lblTaBortPersonal.setText("Välj personal som ska tas bort");

        lblTaBortPersonalEpost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTaBortPersonalEpost.setForeground(new java.awt.Color(102, 102, 102));
        lblTaBortPersonalEpost.setText("Epost:");

        javax.swing.GroupLayout pnlTaBortPersonalLayout = new javax.swing.GroupLayout(pnlTaBortPersonal);
        pnlTaBortPersonal.setLayout(pnlTaBortPersonalLayout);
        pnlTaBortPersonalLayout.setHorizontalGroup(
            pnlTaBortPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaBortPersonalLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(pnlTaBortPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlTaBortPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlTaBortPersonalLayout.createSequentialGroup()
                            .addComponent(lblTaBortPersonalEpost)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbTaBortPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblTaBortEnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTaBortPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTaBortPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTaBortPersonalMeddelande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        pnlTaBortPersonalLayout.setVerticalGroup(
            pnlTaBortPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaBortPersonalLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblTaBortEnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblTaBortPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTaBortPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaBortPersonalEpost)
                    .addComponent(cbTaBortPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaBortPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaBortPersonalMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Ta bort personal", pnlTaBortPersonal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRedigeraPersonal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraPersonal4ActionPerformed
        // Redigerar en kunds information
        if (Validering.harTextFaltetVarde(txtRedigeraPersonalFornamn, lblRedigeraPersonalMeddelande)
            && Validering.harTextFaltetVarde(txtRedigeraPersonalEfternamn, lblRedigeraPersonalMeddelande)
            && Validering.harTextFaltetVarde(pwdRedigeraPersonalLosenord, lblRedigeraPersonalMeddelande)
            && Validering.harTextFaltetVarde(txtRedigeraPersonalEpost, lblRedigeraPersonalMeddelande)) {
            try {
                idb.update("UPDATE personal SET Förnamn='" + txtRedigeraPersonalFornamn.getText() + "', "
                    + "Efternamn='" + txtRedigeraPersonalEfternamn.getText() + "', "
                    + "Epost='" + txtRedigeraPersonalEpost.getText() + "' "
                    + "Lösenord='" + pwdRedigeraPersonalLosenord.getText() + "', "
                    + "WHERE Epost='" + cbRedigeraPersonal.getSelectedItem() + "';");
                lblRedigeraPersonalMeddelande.setText("Personal har ändrats.");
            } catch (InfException fel) {
                lblRedigeraPersonalMeddelande.setText("Ett fel uppstod!");
            }
        }
    }//GEN-LAST:event_btnRedigeraPersonal4ActionPerformed

    private void txtRedigeraPersonalFornamn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRedigeraPersonalFornamn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRedigeraPersonalFornamn4ActionPerformed

    private void pwdRedigeraPersonalLosenord4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdRedigeraPersonalLosenord4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdRedigeraPersonalLosenord4ActionPerformed

    private void btnTaBortPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortPersonalActionPerformed
        // tar bort en personal
        lblTaBortPersonalMeddelande.setText("");
        taBortPersonal();
        cbTaBortPersonal.removeAllItems();
        fyllPersonalEpost();
    }//GEN-LAST:event_btnTaBortPersonalActionPerformed

    private void fyllPersonalEpost () {
        String fraga = "SELECT Epost FROM personal";
        try {
            ArrayList<String> epost = idb.fetchColumn(fraga);
            for (String enEpost : epost ){
            cbRedigeraPersonal.addItem(enEpost);
            cbTaBortPersonal.addItem(enEpost);
            }
        }
        catch(InfException fel) {
            fel.printStackTrace();
        }
    }
    
    private boolean taBortPersonal() {
            try {

                String ruta = (String) cbTaBortPersonal.getSelectedItem();
                String fraga = "SELECT Personal_ID, Epost FROM personal";
                boolean hittad = false;

                ArrayList<HashMap<String, String>> personal = idb.fetchRows(fraga);

                for (HashMap<String, String> enPersonal : personal) {
                    String id = enPersonal.get("Personal_ID");
                    String epost = enPersonal.get("Epost");

                    if (ruta.equalsIgnoreCase(epost)) {
                        idb.update("UPDATE tillverka SET Personal=NULL WHERE Personal='" + id + "'");
                        idb.update("UPDATE hatt_i_order SET Personal_ID=NULL WHERE Personal_ID='" + id + "'");
                        idb.delete("DELETE from personal WHERE Epost='" + ruta + "'");
                        lblTaBortPersonalMeddelande.setText(epost + " har raderats.");
                        hittad = true;
                        return true;
                    }
                }

            } catch (InfException fel) {
                lblTaBortPersonalMeddelande.setText("Ett fel uppstod!");
                fel.printStackTrace();
            }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRedigeraPersonal;
    private javax.swing.JButton btnRedigeraPersonal1;
    private javax.swing.JButton btnRedigeraPersonal2;
    private javax.swing.JButton btnRedigeraPersonal3;
    private javax.swing.JButton btnRedigeraPersonal4;
    private javax.swing.JButton btnTaBortPersonal;
    private javax.swing.JComboBox<String> cbRedigeraPersonal;
    private javax.swing.JComboBox<String> cbRedigeraPersonal1;
    private javax.swing.JComboBox<String> cbRedigeraPersonal2;
    private javax.swing.JComboBox<String> cbRedigeraPersonal3;
    private javax.swing.JComboBox<String> cbRedigeraPersonal4;
    private javax.swing.JComboBox<String> cbTaBortPersonal;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel lblPersonalEfternamn;
    private javax.swing.JLabel lblPersonalEfternamn1;
    private javax.swing.JLabel lblPersonalEfternamn2;
    private javax.swing.JLabel lblPersonalEfternamn3;
    private javax.swing.JLabel lblPersonalEfternamn4;
    private javax.swing.JLabel lblPersonalEpost;
    private javax.swing.JLabel lblPersonalEpost1;
    private javax.swing.JLabel lblPersonalEpost2;
    private javax.swing.JLabel lblPersonalEpost3;
    private javax.swing.JLabel lblPersonalEpost4;
    private javax.swing.JLabel lblPersonalFornamn;
    private javax.swing.JLabel lblPersonalFornamn1;
    private javax.swing.JLabel lblPersonalFornamn2;
    private javax.swing.JLabel lblPersonalFornamn3;
    private javax.swing.JLabel lblPersonalFornamn4;
    private javax.swing.JLabel lblPersonalLosenord;
    private javax.swing.JLabel lblPersonalLosenord1;
    private javax.swing.JLabel lblPersonalLosenord2;
    private javax.swing.JLabel lblPersonalLosenord3;
    private javax.swing.JLabel lblPersonalLosenord4;
    private javax.swing.JLabel lblRedigeraPersonal;
    private javax.swing.JLabel lblRedigeraPersonal1;
    private javax.swing.JLabel lblRedigeraPersonal2;
    private javax.swing.JLabel lblRedigeraPersonal3;
    private javax.swing.JLabel lblRedigeraPersonal4;
    private javax.swing.JLabel lblRedigeraPersonalMeddelande;
    private javax.swing.JLabel lblRedigeraPersonalMeddelande1;
    private javax.swing.JLabel lblRedigeraPersonalMeddelande2;
    private javax.swing.JLabel lblRedigeraPersonalMeddelande3;
    private javax.swing.JLabel lblRedigeraPersonalMeddelande4;
    private javax.swing.JLabel lblRedigeraPersonalValj;
    private javax.swing.JLabel lblRedigeraPersonalValj1;
    private javax.swing.JLabel lblRedigeraPersonalValj2;
    private javax.swing.JLabel lblRedigeraPersonalValj3;
    private javax.swing.JLabel lblRedigeraPersonalValj4;
    private javax.swing.JLabel lblTaBortEnPersonal;
    private javax.swing.JLabel lblTaBortPersonal;
    private javax.swing.JLabel lblTaBortPersonalEpost;
    private javax.swing.JLabel lblTaBortPersonalMeddelande;
    private javax.swing.JPanel pnlRedigeraPersonal;
    private javax.swing.JPanel pnlRedigeraPersonal1;
    private javax.swing.JPanel pnlRedigeraPersonal2;
    private javax.swing.JPanel pnlRedigeraPersonal3;
    private javax.swing.JPanel pnlRedigeraPersonal4;
    private javax.swing.JPanel pnlTaBortPersonal;
    private javax.swing.JPasswordField pwdRedigeraPersonalLosenord;
    private javax.swing.JPasswordField pwdRedigeraPersonalLosenord1;
    private javax.swing.JPasswordField pwdRedigeraPersonalLosenord2;
    private javax.swing.JPasswordField pwdRedigeraPersonalLosenord3;
    private javax.swing.JPasswordField pwdRedigeraPersonalLosenord4;
    private javax.swing.JTextField txtRedigeraPersonalEfternamn;
    private javax.swing.JTextField txtRedigeraPersonalEfternamn1;
    private javax.swing.JTextField txtRedigeraPersonalEfternamn2;
    private javax.swing.JTextField txtRedigeraPersonalEfternamn3;
    private javax.swing.JTextField txtRedigeraPersonalEfternamn4;
    private javax.swing.JTextField txtRedigeraPersonalEpost;
    private javax.swing.JTextField txtRedigeraPersonalEpost1;
    private javax.swing.JTextField txtRedigeraPersonalEpost2;
    private javax.swing.JTextField txtRedigeraPersonalEpost3;
    private javax.swing.JTextField txtRedigeraPersonalEpost4;
    private javax.swing.JTextField txtRedigeraPersonalFornamn;
    private javax.swing.JTextField txtRedigeraPersonalFornamn1;
    private javax.swing.JTextField txtRedigeraPersonalFornamn2;
    private javax.swing.JTextField txtRedigeraPersonalFornamn3;
    private javax.swing.JTextField txtRedigeraPersonalFornamn4;
    // End of variables declaration//GEN-END:variables
}
