package System;

import javax.swing.JFrame;
import oru.inf.InfDB;

/**
 *
 * @author leyla
 */
public class Dashboard extends javax.swing.JFrame {
    
    private InfDB idb;
    /**
     * Creates new form test
     */
    public Dashboard(InfDB idb) {
        initComponents();
        this.idb = idb;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSideBarVanster = new javax.swing.JPanel();
        lblTest = new javax.swing.JLabel();
        lblTest1 = new javax.swing.JLabel();
        btnOrdersida = new javax.swing.JButton();
        btnPersonalsida = new javax.swing.JButton();
        btnSkapaHatt = new javax.swing.JButton();
        btnSkapaOrder = new javax.swing.JButton();
        btnValjHatt = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        btnStartsida = new javax.swing.JButton();
        lblNuvarandeAnvandare = new javax.swing.JLabel();
        btnRadera1 = new javax.swing.JButton();
        pnlMitten = new javax.swing.JPanel();
        pnlOrdersida = new javax.swing.JPanel();
        pnlPersonalsida = new javax.swing.JPanel();
        btnRedigeraKund = new javax.swing.JButton();
        btnRedigeraKund1 = new javax.swing.JButton();
        pnlSkapaHatt = new javax.swing.JPanel();
        pnlSkapaKund = new javax.swing.JPanel();
        pnlSkapaOrder = new javax.swing.JPanel();
        pnlValjHatt = new javax.swing.JPanel();
        pnl1Valkommen = new javax.swing.JPanel();
        pnlSideBarHoger = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSideBarVanster.setBackground(new java.awt.Color(51, 51, 51));

        lblTest.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTest.setForeground(new java.awt.Color(255, 255, 255));
        lblTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTest.setText("Hattmakaren");

        lblTest1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTest1.setForeground(new java.awt.Color(255, 255, 255));
        lblTest1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTest1.setText("Personal");

        btnOrdersida.setBackground(new java.awt.Color(0, 51, 153));
        btnOrdersida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOrdersida.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdersida.setText("Ordersida");
        btnOrdersida.setBorder(null);
        btnOrdersida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersidaActionPerformed(evt);
            }
        });

        btnPersonalsida.setBackground(new java.awt.Color(0, 51, 153));
        btnPersonalsida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPersonalsida.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalsida.setText("Personalsida");
        btnPersonalsida.setBorder(null);
        btnPersonalsida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalsidaActionPerformed(evt);
            }
        });

        btnSkapaHatt.setBackground(new java.awt.Color(0, 51, 153));
        btnSkapaHatt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSkapaHatt.setForeground(new java.awt.Color(255, 255, 255));
        btnSkapaHatt.setText("Skapa hatt");
        btnSkapaHatt.setBorder(null);
        btnSkapaHatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaHattActionPerformed(evt);
            }
        });

        btnSkapaOrder.setBackground(new java.awt.Color(0, 51, 153));
        btnSkapaOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSkapaOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnSkapaOrder.setText("Skapa order");
        btnSkapaOrder.setBorder(null);
        btnSkapaOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaOrderActionPerformed(evt);
            }
        });

        btnValjHatt.setBackground(new java.awt.Color(0, 51, 153));
        btnValjHatt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnValjHatt.setForeground(new java.awt.Color(255, 255, 255));
        btnValjHatt.setText("Välj hatt");
        btnValjHatt.setBorder(null);
        btnValjHatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjHattActionPerformed(evt);
            }
        });

        btnLoggaUt.setBackground(new java.awt.Color(153, 0, 0));
        btnLoggaUt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoggaUt.setForeground(new java.awt.Color(255, 255, 255));
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.setBorder(null);
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        btnStartsida.setBackground(new java.awt.Color(0, 51, 153));
        btnStartsida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStartsida.setForeground(new java.awt.Color(255, 255, 255));
        btnStartsida.setText("Startsida");
        btnStartsida.setBorder(null);
        btnStartsida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartsidaActionPerformed(evt);
            }
        });

        lblNuvarandeAnvandare.setForeground(new java.awt.Color(0, 102, 0));

        btnRadera1.setBackground(new java.awt.Color(0, 51, 153));
        btnRadera1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRadera1.setForeground(new java.awt.Color(255, 255, 255));
        btnRadera1.setText("Knapp");
        btnRadera1.setBorder(null);
        btnRadera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadera1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSideBarVansterLayout = new javax.swing.GroupLayout(pnlSideBarVanster);
        pnlSideBarVanster.setLayout(pnlSideBarVansterLayout);
        pnlSideBarVansterLayout.setHorizontalGroup(
            pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarVansterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideBarVansterLayout.createSequentialGroup()
                        .addComponent(lblTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNuvarandeAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSkapaHatt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSkapaOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValjHatt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoggaUt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPersonalsida, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addComponent(btnOrdersida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStartsida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRadera1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTest, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSideBarVansterLayout.setVerticalGroup(
            pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarVansterLayout.createSequentialGroup()
                .addGroup(pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideBarVansterLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblNuvarandeAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBarVansterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnStartsida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrdersida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonalsida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSkapaHatt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSkapaOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnValjHatt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRadera1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pnlMitten.setBackground(new java.awt.Color(255, 255, 255));
        pnlMitten.setLayout(new java.awt.CardLayout());

        pnlOrdersida.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout pnlOrdersidaLayout = new javax.swing.GroupLayout(pnlOrdersida);
        pnlOrdersida.setLayout(pnlOrdersidaLayout);
        pnlOrdersidaLayout.setHorizontalGroup(
            pnlOrdersidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlOrdersidaLayout.setVerticalGroup(
            pnlOrdersidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlOrdersida, "card4");

        pnlPersonalsida.setBackground(new java.awt.Color(102, 102, 102));

        btnRedigeraKund.setBackground(new java.awt.Color(0, 51, 102));
        btnRedigeraKund.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRedigeraKund.setForeground(new java.awt.Color(255, 255, 255));
        btnRedigeraKund.setText("Redigera kundinformation");

        btnRedigeraKund1.setBackground(new java.awt.Color(0, 51, 102));
        btnRedigeraKund1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRedigeraKund1.setForeground(new java.awt.Color(255, 255, 255));
        btnRedigeraKund1.setText("Redigera kundinformation");

        javax.swing.GroupLayout pnlPersonalsidaLayout = new javax.swing.GroupLayout(pnlPersonalsida);
        pnlPersonalsida.setLayout(pnlPersonalsidaLayout);
        pnlPersonalsidaLayout.setHorizontalGroup(
            pnlPersonalsidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalsidaLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(pnlPersonalsidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRedigeraKund, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRedigeraKund1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        pnlPersonalsidaLayout.setVerticalGroup(
            pnlPersonalsidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalsidaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnRedigeraKund, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnRedigeraKund1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        pnlMitten.add(pnlPersonalsida, "card4");

        pnlSkapaHatt.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout pnlSkapaHattLayout = new javax.swing.GroupLayout(pnlSkapaHatt);
        pnlSkapaHatt.setLayout(pnlSkapaHattLayout);
        pnlSkapaHattLayout.setHorizontalGroup(
            pnlSkapaHattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlSkapaHattLayout.setVerticalGroup(
            pnlSkapaHattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlSkapaHatt, "card4");

        pnlSkapaKund.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout pnlSkapaKundLayout = new javax.swing.GroupLayout(pnlSkapaKund);
        pnlSkapaKund.setLayout(pnlSkapaKundLayout);
        pnlSkapaKundLayout.setHorizontalGroup(
            pnlSkapaKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlSkapaKundLayout.setVerticalGroup(
            pnlSkapaKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlSkapaKund, "card4");

        pnlSkapaOrder.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout pnlSkapaOrderLayout = new javax.swing.GroupLayout(pnlSkapaOrder);
        pnlSkapaOrder.setLayout(pnlSkapaOrderLayout);
        pnlSkapaOrderLayout.setHorizontalGroup(
            pnlSkapaOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlSkapaOrderLayout.setVerticalGroup(
            pnlSkapaOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlSkapaOrder, "card4");

        pnlValjHatt.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout pnlValjHattLayout = new javax.swing.GroupLayout(pnlValjHatt);
        pnlValjHatt.setLayout(pnlValjHattLayout);
        pnlValjHattLayout.setHorizontalGroup(
            pnlValjHattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlValjHattLayout.setVerticalGroup(
            pnlValjHattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlValjHatt, "card4");

        pnl1Valkommen.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnl1ValkommenLayout = new javax.swing.GroupLayout(pnl1Valkommen);
        pnl1Valkommen.setLayout(pnl1ValkommenLayout);
        pnl1ValkommenLayout.setHorizontalGroup(
            pnl1ValkommenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnl1ValkommenLayout.setVerticalGroup(
            pnl1ValkommenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnl1Valkommen, "card4");

        pnlSideBarHoger.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pnlSideBarHogerLayout = new javax.swing.GroupLayout(pnlSideBarHoger);
        pnlSideBarHoger.setLayout(pnlSideBarHogerLayout);
        pnlSideBarHogerLayout.setHorizontalGroup(
            pnlSideBarHogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        pnlSideBarHogerLayout.setVerticalGroup(
            pnlSideBarHogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSideBarVanster, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlMitten, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSideBarHoger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideBarVanster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSideBarHoger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMitten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        // Loggar ut användaren och skickar till startsidan
       /* Inloggning inloggning = new Inloggning(idb);
        inloggning.show();
        dispose();*/
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnRadera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadera1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRadera1ActionPerformed

    private void btnValjHattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjHattActionPerformed
        panelerGomda();
        pnlValjHatt.show();
    }//GEN-LAST:event_btnValjHattActionPerformed

    private void btnPersonalsidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalsidaActionPerformed
        panelerGomda();
        pnlPersonalsida.show();
    }//GEN-LAST:event_btnPersonalsidaActionPerformed

    private void btnSkapaHattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaHattActionPerformed
        panelerGomda();
        pnlSkapaHatt.show();
    }//GEN-LAST:event_btnSkapaHattActionPerformed

    private void btnSkapaOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaOrderActionPerformed
        panelerGomda();
        pnlSkapaOrder.show();
    }//GEN-LAST:event_btnSkapaOrderActionPerformed

    private void btnOrdersidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersidaActionPerformed
        panelerGomda();
        pnlOrdersida.show();
    }//GEN-LAST:event_btnOrdersidaActionPerformed

    private void btnStartsidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartsidaActionPerformed
        panelerGomda();
        pnl1Valkommen.show();
    }//GEN-LAST:event_btnStartsidaActionPerformed

    private void panelerGomda() {
        //Alla gömda paneler samlade i en metod för att förenkla koden
        pnl1Valkommen.hide();
        pnlSkapaHatt.hide();
        pnlPersonalsida.hide();
        pnlOrdersida.hide();
        pnlValjHatt.hide();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnOrdersida;
    private javax.swing.JButton btnPersonalsida;
    private javax.swing.JButton btnRadera1;
    private javax.swing.JButton btnRedigeraKund;
    private javax.swing.JButton btnRedigeraKund1;
    private javax.swing.JButton btnSkapaHatt;
    private javax.swing.JButton btnSkapaOrder;
    private javax.swing.JButton btnStartsida;
    private javax.swing.JButton btnValjHatt;
    private javax.swing.JLabel lblNuvarandeAnvandare;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JPanel pnl1Valkommen;
    private javax.swing.JPanel pnlMitten;
    private javax.swing.JPanel pnlOrdersida;
    private javax.swing.JPanel pnlPersonalsida;
    private javax.swing.JPanel pnlSideBarHoger;
    private javax.swing.JPanel pnlSideBarVanster;
    private javax.swing.JPanel pnlSkapaHatt;
    private javax.swing.JPanel pnlSkapaKund;
    private javax.swing.JPanel pnlSkapaOrder;
    private javax.swing.JPanel pnlValjHatt;
    // End of variables declaration//GEN-END:variables
}
