package System;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author leyla
 */
public class Dashboard extends javax.swing.JFrame {
    
    private InfDB idb;
    /**
     * Creates new form test
     */
    public Dashboard() {
        try {
            idb = new InfDB("hattmakarna", "3306", "hattmakarna", "team5key");
        } catch (InfException ex) {
            Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSideBarVanster = new javax.swing.JPanel();
        lblTest = new javax.swing.JLabel();
        lblTest1 = new javax.swing.JLabel();
        btnRegistrera = new javax.swing.JButton();
        btnAndraInformation = new javax.swing.JButton();
        btnTaBortUtrustning = new javax.swing.JButton();
        btnGeAdmin = new javax.swing.JButton();
        btnRadera = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        btnAgentStartsida = new javax.swing.JButton();
        lblNuvarandeAnvandare = new javax.swing.JLabel();
        btnRadera1 = new javax.swing.JButton();
        pnlMitten = new javax.swing.JPanel();
        pnlOrdersida = new javax.swing.JPanel();
        pnlPersonalsida = new javax.swing.JPanel();
        pnlSkapaHatt = new javax.swing.JPanel();
        pnlSkapaKund = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        pnlSkapaOrder = new javax.swing.JPanel();
        pnl1Valkommen = new javax.swing.JPanel();
        pnlSideBarHoger = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSideBarVanster.setBackground(new java.awt.Color(51, 51, 51));

        lblTest.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTest.setForeground(new java.awt.Color(255, 255, 255));
        lblTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTest.setText("Test");

        lblTest1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTest1.setForeground(new java.awt.Color(255, 255, 255));
        lblTest1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTest1.setText("test");

        btnRegistrera.setBackground(new java.awt.Color(0, 51, 153));
        btnRegistrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrera.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrera.setText("Registrera");
        btnRegistrera.setBorder(null);
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        btnAndraInformation.setBackground(new java.awt.Color(0, 51, 153));
        btnAndraInformation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAndraInformation.setForeground(new java.awt.Color(255, 255, 255));
        btnAndraInformation.setText("Ändra information");
        btnAndraInformation.setBorder(null);
        btnAndraInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInformationActionPerformed(evt);
            }
        });

        btnTaBortUtrustning.setBackground(new java.awt.Color(0, 51, 153));
        btnTaBortUtrustning.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTaBortUtrustning.setForeground(new java.awt.Color(255, 255, 255));
        btnTaBortUtrustning.setText("Ta bort ");
        btnTaBortUtrustning.setBorder(null);
        btnTaBortUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortUtrustningActionPerformed(evt);
            }
        });

        btnGeAdmin.setBackground(new java.awt.Color(0, 51, 153));
        btnGeAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGeAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnGeAdmin.setText("Ge status");
        btnGeAdmin.setBorder(null);
        btnGeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeAdminActionPerformed(evt);
            }
        });

        btnRadera.setBackground(new java.awt.Color(0, 51, 153));
        btnRadera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRadera.setForeground(new java.awt.Color(255, 255, 255));
        btnRadera.setText("Radera");
        btnRadera.setBorder(null);
        btnRadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaActionPerformed(evt);
            }
        });

        btnLoggaUt.setBackground(new java.awt.Color(153, 0, 0));
        btnLoggaUt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoggaUt.setForeground(new java.awt.Color(255, 255, 255));
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.setBorder(null);
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        btnAgentStartsida.setBackground(new java.awt.Color(0, 51, 153));
        btnAgentStartsida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgentStartsida.setForeground(new java.awt.Color(255, 255, 255));
        btnAgentStartsida.setText("Startsida");
        btnAgentStartsida.setBorder(null);
        btnAgentStartsida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgentStartsidaActionPerformed(evt);
            }
        });

        lblNuvarandeAnvandare.setForeground(new java.awt.Color(0, 102, 0));

        btnRadera1.setBackground(new java.awt.Color(0, 51, 153));
        btnRadera1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRadera1.setForeground(new java.awt.Color(255, 255, 255));
        btnRadera1.setText("Radera");
        btnRadera1.setBorder(null);
        btnRadera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadera1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSideBarVansterLayout = new javax.swing.GroupLayout(pnlSideBarVanster);
        pnlSideBarVanster.setLayout(pnlSideBarVansterLayout);
        pnlSideBarVansterLayout.setHorizontalGroup(
            pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarVansterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideBarVansterLayout.createSequentialGroup()
                        .addComponent(lblTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNuvarandeAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTaBortUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRadera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoggaUt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAndraInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addComponent(btnRegistrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgentStartsida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRadera1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTest, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSideBarVansterLayout.setVerticalGroup(
            pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarVansterLayout.createSequentialGroup()
                .addGroup(pnlSideBarVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideBarVansterLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblNuvarandeAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBarVansterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnAgentStartsida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAndraInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaBortUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRadera1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pnlMitten.setBackground(new java.awt.Color(255, 255, 255));
        pnlMitten.setLayout(new java.awt.CardLayout());

        pnlOrdersida.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout pnlOrdersidaLayout = new javax.swing.GroupLayout(pnlOrdersida);
        pnlOrdersida.setLayout(pnlOrdersidaLayout);
        pnlOrdersidaLayout.setHorizontalGroup(
            pnlOrdersidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlOrdersidaLayout.setVerticalGroup(
            pnlOrdersidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlOrdersida, "card4");

        pnlPersonalsida.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout pnlPersonalsidaLayout = new javax.swing.GroupLayout(pnlPersonalsida);
        pnlPersonalsida.setLayout(pnlPersonalsidaLayout);
        pnlPersonalsidaLayout.setHorizontalGroup(
            pnlPersonalsidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlPersonalsidaLayout.setVerticalGroup(
            pnlPersonalsidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlPersonalsida, "card4");

        pnlSkapaHatt.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout pnlSkapaHattLayout = new javax.swing.GroupLayout(pnlSkapaHatt);
        pnlSkapaHatt.setLayout(pnlSkapaHattLayout);
        pnlSkapaHattLayout.setHorizontalGroup(
            pnlSkapaHattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlSkapaHattLayout.setVerticalGroup(
            pnlSkapaHattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlSkapaHatt, "card4");

        pnlSkapaKund.setBackground(new java.awt.Color(51, 153, 0));

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Material-ID", "Namn", "Beskrivning"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMaterial.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblMaterial);
        if (tblMaterial.getColumnModel().getColumnCount() > 0) {
            tblMaterial.getColumnModel().getColumn(2).setMinWidth(1000);
            tblMaterial.getColumnModel().getColumn(2).setMaxWidth(1200);
        }

        javax.swing.GroupLayout pnlSkapaKundLayout = new javax.swing.GroupLayout(pnlSkapaKund);
        pnlSkapaKund.setLayout(pnlSkapaKundLayout);
        pnlSkapaKundLayout.setHorizontalGroup(
            pnlSkapaKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        pnlSkapaKundLayout.setVerticalGroup(
            pnlSkapaKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlSkapaKund, "card4");

        pnlSkapaOrder.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout pnlSkapaOrderLayout = new javax.swing.GroupLayout(pnlSkapaOrder);
        pnlSkapaOrder.setLayout(pnlSkapaOrderLayout);
        pnlSkapaOrderLayout.setHorizontalGroup(
            pnlSkapaOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnlSkapaOrderLayout.setVerticalGroup(
            pnlSkapaOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnlSkapaOrder, "card4");

        pnl1Valkommen.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout pnl1ValkommenLayout = new javax.swing.GroupLayout(pnl1Valkommen);
        pnl1Valkommen.setLayout(pnl1ValkommenLayout);
        pnl1ValkommenLayout.setHorizontalGroup(
            pnl1ValkommenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
        );
        pnl1ValkommenLayout.setVerticalGroup(
            pnl1ValkommenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        pnlMitten.add(pnl1Valkommen, "card4");

        pnlSideBarHoger.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pnlSideBarHogerLayout = new javax.swing.GroupLayout(pnlSideBarHoger);
        pnlSideBarHoger.setLayout(pnlSideBarHogerLayout);
        pnlSideBarHogerLayout.setHorizontalGroup(
            pnlSideBarHogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        pnlSideBarHogerLayout.setVerticalGroup(
            pnlSideBarHogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSideBarVanster, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlMitten, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSideBarHoger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideBarVanster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSideBarHoger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMitten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        // Loggar ut användaren och skickar till startsidan
       /* Inloggning inloggning = new Inloggning(idb);
        inloggning.show();
        dispose();*/
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnRadera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadera1ActionPerformed
            // TODO add your handling code here:
            panelerGomda();
            pnlSkapaKund.show();

            

            String sqlFraga = "SELECT Material_ID FROM Material";



            String getMaterialInfo = "SELECT * FROM Material";



            try {
                ArrayList<HashMap<String, String>> materialInfo = idb.fetchRows(getMaterialInfo);

                ArrayList<String> antalMaterial = idb.fetchColumn(sqlFraga);

                int antalMaterialInt = antalMaterial.size();

                int i = 0;
                    while(i<antalMaterialInt)
                    {
                for(HashMap<String, String> enHashMap : materialInfo)
                {

                    String materialID = enHashMap.get("Material_ID");
                    String namn = enHashMap.get("Namn");
                    String beskrivning = enHashMap.get("Beskrivning");



                    int j = 0;
                        while(j<3)
                        {
                            tblMaterial.setValueAt(materialID, i, j);
                            j++;
                            tblMaterial.setValueAt(namn, i, j);
                            j++;
                            tblMaterial.setValueAt(beskrivning, i, j);
                            j++;
                        }
                    i++;
                    }    

                }
            } catch (InfException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
           
        
        
        
    }//GEN-LAST:event_btnRadera1ActionPerformed

    private void btnRaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaActionPerformed
        // Knappen tar en till sidan för att ta bort alien/agent
        panelerGomda();
        pnl1Valkommen.show();
    }//GEN-LAST:event_btnRaderaActionPerformed

    private void btnAndraInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInformationActionPerformed
        // Tar en till sidan för att ändra info om agent/alien
        panelerGomda();
        pnlPersonalsida.show();
    }//GEN-LAST:event_btnAndraInformationActionPerformed

    private void btnTaBortUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortUtrustningActionPerformed
        // Knapp i sidebar som tar en till funktion för att ta bort utrustning ur systemet
        panelerGomda();
        pnlOrdersida.show();
    }//GEN-LAST:event_btnTaBortUtrustningActionPerformed

    private void btnGeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeAdminActionPerformed
        // Tar en till sidan för att ge agent adminsstatus
        panelerGomda();
        pnlSkapaHatt.show();
    }//GEN-LAST:event_btnGeAdminActionPerformed

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
        // Knappp i sidebar för att ta användaren till registrering av agenter/aliens
        panelerGomda();
        pnl1Valkommen.show();
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void btnAgentStartsidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgentStartsidaActionPerformed
        // Knappen som tar en till startsidan för admindashboard
        panelerGomda();
        pnl1Valkommen.show();
    }//GEN-LAST:event_btnAgentStartsidaActionPerformed

    private void panelerGomda() {
        //Alla gömda paneler samlade i en metod för att förenkla koden
        pnl1Valkommen.hide();
        pnlSkapaHatt.hide();
        pnlPersonalsida.hide();
        pnlOrdersida.hide();
    }
    
    public static void main(String[] args) {
        // Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgentStartsida;
    private javax.swing.JButton btnAndraInformation;
    private javax.swing.JButton btnGeAdmin;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnRadera;
    private javax.swing.JButton btnRadera1;
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnTaBortUtrustning;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNuvarandeAnvandare;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JPanel pnl1Valkommen;
    private javax.swing.JPanel pnlMitten;
    private javax.swing.JPanel pnlOrdersida;
    private javax.swing.JPanel pnlPersonalsida;
    private javax.swing.JPanel pnlSideBarHoger;
    private javax.swing.JPanel pnlSideBarVanster;
    private javax.swing.JPanel pnlSkapaHatt;
    private javax.swing.JPanel pnlSkapaKund;
    private javax.swing.JPanel pnlSkapaOrder;
    private javax.swing.JTable tblMaterial;
    // End of variables declaration//GEN-END:variables
}
