package System;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author sarah
 */
public class InloggningsSida extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form InloggningsSida
     */
    public InloggningsSida(InfDB idb) {
        initComponents();
        this.idb = idb;
        //Dessa två första använda för att man ska kunna få upp felmedelande om man skriver in fel epost eller lösenord
        lblFelAnvNamn.setVisible(false);
        lblFelLosen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggningHoger = new javax.swing.JPanel();
        txtAnvNamn = new javax.swing.JTextField();
        lblAnvNamn = new javax.swing.JLabel();
        lblLosen = new javax.swing.JLabel();
        txtLosen = new javax.swing.JPasswordField();
        lblFelLosen = new javax.swing.JLabel();
        lblFelAnvNamn = new javax.swing.JLabel();
        btnLoggaIn = new javax.swing.JButton();
        lblMeddelande = new javax.swing.JLabel();
        lblInloggningVanster = new javax.swing.JPanel();
        lblInloggningValkommen = new javax.swing.JLabel();
        lblInloggningHattmakeri = new javax.swing.JLabel();
        lblInloggningBild = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInloggningHoger.setBackground(new java.awt.Color(25, 41, 63));

        txtAnvNamn.setBackground(new java.awt.Color(25, 41, 63));
        txtAnvNamn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        txtAnvNamn.setForeground(new java.awt.Color(255, 255, 255));
        txtAnvNamn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        lblAnvNamn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        lblAnvNamn.setForeground(new java.awt.Color(255, 255, 255));
        lblAnvNamn.setText("Användarnamn");

        lblLosen.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        lblLosen.setForeground(new java.awt.Color(255, 255, 255));
        lblLosen.setText("Lösenord");

        txtLosen.setBackground(new java.awt.Color(25, 41, 63));
        txtLosen.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        txtLosen.setForeground(new java.awt.Color(255, 255, 255));
        txtLosen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 255, 255)));

        lblFelLosen.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        lblFelLosen.setForeground(new java.awt.Color(255, 255, 255));
        lblFelLosen.setText("Fel lösenord");

        lblFelAnvNamn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        lblFelAnvNamn.setForeground(new java.awt.Color(255, 255, 255));
        lblFelAnvNamn.setText("Epost existerar ej");

        btnLoggaIn.setBackground(new java.awt.Color(0, 102, 102));
        btnLoggaIn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        btnLoggaIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        lblMeddelande.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblInloggningVanster.setBackground(new java.awt.Color(0, 102, 102));

        lblInloggningValkommen.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 36)); // NOI18N
        lblInloggningValkommen.setForeground(new java.awt.Color(255, 255, 255));
        lblInloggningValkommen.setText("Välkommen");

        lblInloggningHattmakeri.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        lblInloggningHattmakeri.setText("Ottos hattmakeri");

        lblInloggningBild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bild/otto.png"))); // NOI18N
        lblInloggningBild.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(17, 32, 45), 10));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout lblInloggningVansterLayout = new javax.swing.GroupLayout(lblInloggningVanster);
        lblInloggningVanster.setLayout(lblInloggningVansterLayout);
        lblInloggningVansterLayout.setHorizontalGroup(
            lblInloggningVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblInloggningVansterLayout.createSequentialGroup()
                .addGroup(lblInloggningVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblInloggningVansterLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblInloggningValkommen, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblInloggningVansterLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblInloggningHattmakeri))
                    .addGroup(lblInloggningVansterLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblInloggningBild))
                    .addGroup(lblInloggningVansterLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(lblInloggningVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblInloggningVansterLayout.createSequentialGroup()
                    .addContainerGap(100, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(108, 108, 108)))
        );
        lblInloggningVansterLayout.setVerticalGroup(
            lblInloggningVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblInloggningVansterLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblInloggningValkommen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInloggningHattmakeri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInloggningBild)
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(lblInloggningVansterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblInloggningVansterLayout.createSequentialGroup()
                    .addContainerGap(483, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)))
        );

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel4.setText("Logga in");

        javax.swing.GroupLayout lblInloggningHogerLayout = new javax.swing.GroupLayout(lblInloggningHoger);
        lblInloggningHoger.setLayout(lblInloggningHogerLayout);
        lblInloggningHogerLayout.setHorizontalGroup(
            lblInloggningHogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblInloggningHogerLayout.createSequentialGroup()
                .addComponent(lblInloggningVanster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(lblInloggningHogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnvNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnvNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelAnvNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lblInloggningHogerLayout.createSequentialGroup()
                        .addComponent(lblFelLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(lblInloggningHogerLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(lblMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblInloggningHogerLayout.setVerticalGroup(
            lblInloggningHogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInloggningVanster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lblInloggningHogerLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblAnvNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtAnvNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblFelAnvNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(lblInloggningHogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFelLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(lblInloggningHogerLayout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(lblMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(lblInloggningHoger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        //Detta är en kod som använda för att loopa igenom två arraylist för att hitta om det är rätt eller fel lösenord/epost
        try {
            if (Validering.harTextFaltetVarde(txtAnvNamn, lblMeddelande) && Validering.harTextFaltetVarde(txtLosen, lblMeddelande)) {
                // TODO add your handling code here:
                String anvNamn = txtAnvNamn.getText().toLowerCase();
                char[] passwordChars = txtLosen.getPassword();
                String losen = new String(passwordChars);

                ArrayList<String> epostLista = idb.fetchColumn("Select Epost from Personal");
                ArrayList<String> losenLista = idb.fetchColumn("Select Lösenord from Personal");

                boolean hittadEpost = false;
                for (int i = 0; i < epostLista.size() && hittadEpost == false; i++) {
                    String epost = epostLista.get(i).toLowerCase();
                    if (epost.equals(anvNamn)) {
                        hittadEpost = true;
                        lblFelAnvNamn.setVisible(false);
                    }
                }
                if (hittadEpost == false) {
                    lblFelAnvNamn.setVisible(true);
                } else {
                    boolean hittatLosen = false;

                    for (int i = 0; i < losenLista.size() && hittatLosen == false; i++) {
                        String losenFranLista = losenLista.get(i);

                        if (losenFranLista.equals(losen)) {
                            hittatLosen = true;
                            lblFelLosen.setVisible(false);
                        }
                    }
                    if (hittatLosen == false) {
                        lblFelLosen.setVisible(true);
                    }

                    if (hittatLosen == true && hittadEpost == true) {
                        String personalId = idb.fetchSingle("Select Personal_ID from personal where epost = '" + txtAnvNamn.getText() + "'");
                        
                        Dashboard dashboard = new Dashboard(idb, personalId);
                        dashboard.show();
                        dispose();
                    }
                }
            }

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnLoggaInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAnvNamn;
    private javax.swing.JLabel lblFelAnvNamn;
    private javax.swing.JLabel lblFelLosen;
    private javax.swing.JLabel lblInloggningBild;
    private javax.swing.JLabel lblInloggningHattmakeri;
    private javax.swing.JPanel lblInloggningHoger;
    private javax.swing.JLabel lblInloggningValkommen;
    private javax.swing.JPanel lblInloggningVanster;
    private javax.swing.JLabel lblLosen;
    private javax.swing.JLabel lblMeddelande;
    private javax.swing.JTextField txtAnvNamn;
    private javax.swing.JPasswordField txtLosen;
    // End of variables declaration//GEN-END:variables
}
