/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;

/**
 *
 * @author leyla
 */
public class Personaldetaljer extends javax.swing.JFrame {

    /**
     * Creates new form Personaldetaljer
     */
    public Personaldetaljer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRedigeraKund = new javax.swing.JPanel();
        lblPersonalFornamn = new javax.swing.JLabel();
        txtPostnummer = new javax.swing.JTextField();
        lblPersonalLosenord = new javax.swing.JLabel();
        btnRedigeraKund1 = new javax.swing.JButton();
        lblPersonalEpost = new javax.swing.JLabel();
        lblAndraKundMeddelande = new javax.swing.JLabel();
        lblRedigeraPersonalValj = new javax.swing.JLabel();
        txtFornamn = new javax.swing.JTextField();
        txtEfternamn = new javax.swing.JTextField();
        lblPersonalEfternamn = new javax.swing.JLabel();
        cbRedigeraPersonal = new javax.swing.JComboBox<>();
        lblRedigeraPersonal = new javax.swing.JLabel();
        pwdRedigeraPersonalLosenord = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRedigeraKund.setBackground(new java.awt.Color(255, 255, 255));

        lblPersonalFornamn.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonalFornamn.setText("Förnamn:");

        txtPostnummer.setBackground(new java.awt.Color(153, 153, 153));
        txtPostnummer.setForeground(new java.awt.Color(0, 0, 0));

        lblPersonalLosenord.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonalLosenord.setText("Lösenord:");

        btnRedigeraKund1.setBackground(new java.awt.Color(0, 102, 153));
        btnRedigeraKund1.setForeground(new java.awt.Color(255, 255, 255));
        btnRedigeraKund1.setText("Redigera kund");
        btnRedigeraKund1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraKund1ActionPerformed(evt);
            }
        });

        lblPersonalEpost.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonalEpost.setText("Nytt epost:");

        lblAndraKundMeddelande.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAndraKundMeddelande.setForeground(new java.awt.Color(0, 0, 0));

        lblRedigeraPersonalValj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRedigeraPersonalValj.setForeground(new java.awt.Color(102, 102, 102));
        lblRedigeraPersonalValj.setText("Välj epost för personal som ska redigeras:");

        txtFornamn.setBackground(new java.awt.Color(153, 153, 153));
        txtFornamn.setForeground(new java.awt.Color(0, 0, 0));
        txtFornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornamnActionPerformed(evt);
            }
        });

        txtEfternamn.setBackground(new java.awt.Color(153, 153, 153));
        txtEfternamn.setForeground(new java.awt.Color(0, 0, 0));

        lblPersonalEfternamn.setForeground(new java.awt.Color(102, 102, 102));
        lblPersonalEfternamn.setText("Efternamn:");

        cbRedigeraPersonal.setForeground(new java.awt.Color(0, 0, 0));

        lblRedigeraPersonal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRedigeraPersonal.setForeground(new java.awt.Color(102, 102, 102));
        lblRedigeraPersonal.setText("Redigera personal");

        pwdRedigeraPersonalLosenord.setBackground(new java.awt.Color(153, 153, 153));
        pwdRedigeraPersonalLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdRedigeraPersonalLosenordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRedigeraKundLayout = new javax.swing.GroupLayout(pnlRedigeraKund);
        pnlRedigeraKund.setLayout(pnlRedigeraKundLayout);
        pnlRedigeraKundLayout.setHorizontalGroup(
            pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedigeraKundLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblRedigeraPersonal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRedigeraPersonalValj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlRedigeraKundLayout.createSequentialGroup()
                            .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlRedigeraKundLayout.createSequentialGroup()
                                    .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPersonalFornamn)
                                        .addComponent(lblPersonalEfternamn)
                                        .addComponent(lblPersonalLosenord))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEfternamn)
                                        .addComponent(pwdRedigeraPersonalLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlRedigeraKundLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPostnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRedigeraKund1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblAndraKundMeddelande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(81, 81, 81)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRedigeraKundLayout.createSequentialGroup()
                        .addComponent(lblPersonalEpost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRedigeraKundLayout.createSequentialGroup()
                        .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRedigeraPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)))
                .addGap(133, 133, 133))
        );
        pnlRedigeraKundLayout.setVerticalGroup(
            pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedigeraKundLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblRedigeraPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblRedigeraPersonalValj)
                .addGap(18, 18, 18)
                .addComponent(cbRedigeraPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalFornamn)
                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalEfternamn)
                    .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalLosenord)
                    .addComponent(pwdRedigeraPersonalLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlRedigeraKundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonalEpost)
                    .addComponent(txtPostnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRedigeraKund1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAndraKundMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 1, Short.MAX_VALUE)
                    .addComponent(pnlRedigeraKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlRedigeraKund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRedigeraKund1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraKund1ActionPerformed
        // Redigerar en kunds information
        if (Validering.harTextFaltetVarde(txtFornamn, lblAndraKundMeddelande)
            && Validering.harTextFaltetVarde(txtEfternamn, lblAndraKundMeddelande)
            && Validering.harTextFaltetVarde(txtGatuadress, lblAndraKundMeddelande)
            && Validering.harTextFaltetVarde(txtPostnummer, lblAndraKundMeddelande)
            && Validering.harTextFaltetVarde(txtOrt, lblAndraKundMeddelande)
            && Validering.harTextFaltetVarde(txtTelefon, lblAndraKundMeddelande)) {
            try {
                idb.update("UPDATE kund SET Förnamn='" + txtFornamn.getText() + "', "
                    + "Efternamn='" + txtEfternamn.getText() + "', "
                    + "Adress='" + txtGatuadress.getText() + "', "
                    + "Postnummer='" + txtPostnummer.getText() + "', "
                    + "Ort='" + txtOrt.getText() + "', "
                    + "Telefon='" + txtTelefon.getText() + "' "
                    + "WHERE Epost='" + cbRedigeraPersonal.getSelectedItem() + "';");
                lblAndraKundMeddelande.setText("Kund har ändrats.");
            } catch (InfException fel) {
                lblAndraKundMeddelande.setText("Ett fel uppstod!");
            }
        }
    }//GEN-LAST:event_btnRedigeraKund1ActionPerformed

    private void txtFornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornamnActionPerformed

    private void pwdRedigeraPersonalLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdRedigeraPersonalLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdRedigeraPersonalLosenordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personaldetaljer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personaldetaljer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personaldetaljer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personaldetaljer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personaldetaljer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRedigeraKund1;
    private javax.swing.JComboBox<String> cbRedigeraPersonal;
    private javax.swing.JLabel lblAndraKundMeddelande;
    private javax.swing.JLabel lblPersonalEfternamn;
    private javax.swing.JLabel lblPersonalEpost;
    private javax.swing.JLabel lblPersonalFornamn;
    private javax.swing.JLabel lblPersonalLosenord;
    private javax.swing.JLabel lblRedigeraPersonal;
    private javax.swing.JLabel lblRedigeraPersonalValj;
    private javax.swing.JPanel pnlRedigeraKund;
    private javax.swing.JPasswordField pwdRedigeraPersonalLosenord;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtPostnummer;
    // End of variables declaration//GEN-END:variables
}
