/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author sarah
 */
public class PnlMaterial extends javax.swing.JPanel {

    private int hattId;
    private InfDB idb;
    /**
     * Creates new form PnlMaterial
     */
    public PnlMaterial(int hattId) {
        initComponents();
        this.hattId= 1;
        try {
            idb = new InfDB("hattmakarna", "3306", "hattmakarna", "team5key");
        } catch (InfException ex) {
            Logger.getLogger(PnlMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        fyllMaterialLista();
    }

    private void fyllMaterialLista()
    {
        try {
            ArrayList<HashMap<String, String>> rader = idb.fetchRows("Select Material_ID, namn from material where Material_ID in (Select Material_ID from material_i_hatt where Hatt_ID = 1)");
            StringBuilder strBuilder = new StringBuilder();
            for(HashMap<String, String> enRad : rader){
               String radInfo = "MaterialId: " + enRad.get("Material_ID") + " Namn: " + enRad.get("Namn") + "\n";
               strBuilder.append(radInfo);
}           String byggdStrang = strBuilder.toString();
            System.out.println(byggdStrang);
            txtInfo.setText(byggdStrang);
       } catch (InfException ex) {
            Logger.getLogger(PnlMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();

        lblRubrik.setText("Materiallista");

        txtInfo.setColumns(20);
        txtInfo.setRows(5);
        jScrollPane1.setViewportView(txtInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRubrik))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblRubrik)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
