
package System;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author leyla
 */
public class RedigeraKund extends javax.swing.JFrame {
    
    private InfDB idb;
    /**
     * Creates new form RedigeraKund
     */
    public RedigeraKund(InfDB idb) {
        this.idb = idb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEfternamn = new javax.swing.JLabel();
        txtOrt = new javax.swing.JTextField();
        lblEpost = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        lblGatuadress = new javax.swing.JLabel();
        btnRedigeraKund = new javax.swing.JButton();
        lblPostnummer = new javax.swing.JLabel();
        lblOrt = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        txtFornamn = new javax.swing.JTextField();
        txtEfternamn = new javax.swing.JTextField();
        txtEpost = new javax.swing.JTextField();
        txtGatuadress = new javax.swing.JTextField();
        lblFornamn = new javax.swing.JLabel();
        txtPostnummer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtKommentar = new javax.swing.JTextField();
        lblMeddelande = new javax.swing.JLabel();
        lblAngeEpost = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEfternamn.setText("Efternamn");

        lblEpost.setText("Epost");

        lblGatuadress.setText("Gatuadress");

        btnRedigeraKund.setBackground(new java.awt.Color(0, 102, 0));
        btnRedigeraKund.setForeground(new java.awt.Color(255, 255, 255));
        btnRedigeraKund.setText("Redigera kund");
        btnRedigeraKund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraKundActionPerformed(evt);
            }
        });

        lblPostnummer.setText("Postnummer ");

        lblOrt.setText("Ort");

        lblTelefon.setText("Telefon");

        txtFornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornamnActionPerformed(evt);
            }
        });

        txtGatuadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGatuadressActionPerformed(evt);
            }
        });

        lblFornamn.setText("Förnamn");

        jLabel1.setText("Kommentar");

        lblAngeEpost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAngeEpost.setText("Skriv in e-post för kund som ska ändras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKommentar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblTelefon)
                                .addGap(37, 37, 37)
                                .addComponent(txtTelefon))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblOrt)
                                .addGap(61, 61, 61)
                                .addComponent(txtOrt))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPostnummer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPostnummer))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblGatuadress)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGatuadress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEfternamn)
                                            .addComponent(lblFornamn)
                                            .addComponent(lblEpost))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEpost)
                                            .addComponent(txtEfternamn)
                                            .addComponent(txtFornamn)))))
                            .addComponent(lblAngeEpost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(btnRedigeraKund)))
                .addGap(290, 290, 290))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAngeEpost)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfternamn)
                    .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGatuadress)
                    .addComponent(txtGatuadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostnummer)
                    .addComponent(txtPostnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKommentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRedigeraKund, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRedigeraKundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraKundActionPerformed
        // Redigerar en kunds information
        if (Validering.harTextFaltetVarde(txtFornamn) && Validering.harTextFaltetVarde(txtEfternamn)
                && Validering.harTextFaltetVarde(txtEpost) && Validering.harTextFaltetVarde(txtGatuadress)
                && Validering.harTextFaltetVarde(txtPostnummer) && Validering.harTextFaltetVarde(txtOrt)
                && Validering.harTextFaltetVarde(txtTelefon)) {
            try {
                idb.update("UPDATE kund SET Förnamn='" + txtFornamn.getText() + "', "
                        + "Efternamn='" + txtEfternamn.getText() + "', "
                        + "Adress='" + txtGatuadress.getText() + "', "
                        + "Postnummer='" + txtPostnummer.getText() + "', "
                        + "Ort='" + txtOrt.getText() + "', "
                        + "Telefon='" + txtTelefon.getText() + "' "
                        + "WHERE Epost='" + txtEpost.getText() + "';");
                lblMeddelande.setText("Kund har ändrats.");
            } catch (InfException fel) {
                lblMeddelande.setText("Ett fel uppstod!");
            }
        }
    }//GEN-LAST:event_btnRedigeraKundActionPerformed

    private void txtFornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornamnActionPerformed

    private void txtGatuadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGatuadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGatuadressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRedigeraKund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAngeEpost;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblGatuadress;
    private javax.swing.JLabel lblMeddelande;
    private javax.swing.JLabel lblOrt;
    private javax.swing.JLabel lblPostnummer;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtGatuadress;
    private javax.swing.JTextField txtKommentar;
    private javax.swing.JTextField txtOrt;
    private javax.swing.JTextField txtPostnummer;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
