/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package System;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList; 
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList; 
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author meyac_2qya4l2
 */
public class ValjHatt1 extends javax.swing.JFrame {
    private static InfDB idb;

    /**
     * Creates new form attValjHatt
     */
    public ValjHatt1(InfDB idb) {
        initComponents();
        this.idb = idb;
//        fyllBox(); 
        fyllBoxOrder();
        fyllBoxHattar();
        listHatt();
        listHattSpecial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbValjAllaHattar = new javax.swing.JComboBox<>();
        cbOrder = new javax.swing.JComboBox<>();
        lblRubrikLaggTIllOrder = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Välj hatt");

        cbValjAllaHattar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbValjAllaHattarActionPerformed(evt);
            }
        });

        lblRubrikLaggTIllOrder.setText("Lägg till i order");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jTabbedPane2.addTab("Visa hattar:", label1);

        jScrollPane1.setViewportView(list1);

        jTabbedPane2.addTab("Lagerförda", jScrollPane1);

        jScrollPane2.setViewportView(list2);

        jTabbedPane2.addTab("Special", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOk)
                    .addComponent(lblRubrikLaggTIllOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbValjAllaHattar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jTabbedPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbValjAllaHattar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblRubrikLaggTIllOrder)
                        .addGap(18, 18, 18)
                        .addComponent(cbOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOk)))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbValjAllaHattarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbValjAllaHattarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbValjAllaHattarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        // TODO add your handling code here:
        try {
            //Hämtar valt objekt från ComboBoxen samt konverterar det till sträng
            String valdOrder = cbOrder.getSelectedItem().toString().toLowerCase();
            //SQL-fråga för att få ProduktID från hatt
            String fragaProduktID = "select Produkt_ID from hatt where Namn = '" + cbValjAllaHattar.getSelectedItem().toString() + "'";
            String ProduktID = idb.fetchSingle(fragaProduktID);
            
            String fragaSkapaHattIOrder = "Insert into hatt_i_order (Order_ID, Hatt_ID) "
            + "Values ('" + valdOrder + "','" + ProduktID + "')";
            idb.insert(fragaSkapaHattIOrder);
            
            JOptionPane.showMessageDialog(null, "Hatt är tillagd i en order!");

        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Error " + ettUndantag.getMessage());
        }

    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void fyllBoxHattar() {
         //fyller combobox med hattar
         String fragaFyllBox = "Select Namn from hatt order by Produkt_ID";
         ArrayList<String> allaHattar;
         try {
             allaHattar = idb.fetchColumn(fragaFyllBox);
             //Varje hatt i listan av hattar itereras över
             for(String hatt : allaHattar) {
                 //Hattens namn läggs till i comboboxen
                 cbValjAllaHattar.addItem(hatt); 
             }
         } catch (InfException ettUndantag) {
             System.out.println("Error " + ettUndantag.getMessage()); 
         }
     }

//         private void fyllBox() {
//         //fyller combobox med godkända hattar
//         String ett = "1";
//         String fragaFyllBox = "Select Namn from hatt where Godkänd = '" + ett + "'" + "order by Produkt_ID";
//         ArrayList<String> allaHattar;
//         try {
//             allaHattar = idb.fetchColumn(fragaFyllBox);
//             //Varje hatt i listan av hattar itereras över
//             for(String hatt : allaHattar) {
//                 //Hattens namn läggs till i comboboxen
//                 cbValjAllaHattar.addItem(hatt); 
//             }
//         } catch (InfException ettUndantag) {
//             JOptionPane.showMessageDialog(null, "Något gick fel");
//             System.out.println("Error " + ettUndantag.getMessage()); 
//         }
//     }
        private void fyllBoxOrder() {
         //fyll combobox med order
         String fragaFyllBox = "Select Order_ID from orders order by Order_ID";
         ArrayList<String> allaOrder;
         try {
             allaOrder = idb.fetchColumn(fragaFyllBox);
             for(String hatt : allaOrder) {
                 cbOrder.addItem(hatt); 
             }
         } catch (InfException ettUndantag) {
             System.out.println("Error " + ettUndantag.getMessage()); 
         }
        } 
        private void listHatt(){
          try {
              String lagerford = "1";
              
            //   = '" + fornamn + "' AND Efternamn = '" + efternamn + "'";
                String fragaHatt = "Select Namn from hatt where Godkänd = 1";
               ArrayList<String> listHatt = idb.fetchColumn(fragaHatt);
                DefaultListModel<String> modelListHatt = new DefaultListModel<>();
                for (String hattNamn : listHatt) {
                 modelListHatt.addElement(hattNamn);
                 list1.setModel(modelListHatt);
                
          }
         } catch (Exception ettUndantag) {
                   
                  }
        }
          private void listHattSpecial(){
          try {
              
                String fragaHatt = "Select Namn from hatt where Godkänd = 0";
               ArrayList<String> listHatt = idb.fetchColumn(fragaHatt);
                DefaultListModel<String> modelListHatt = new DefaultListModel<>();
                for (String hattNamn : listHatt) {
                 modelListHatt.addElement(hattNamn);
                 list2.setModel(modelListHatt);
                
          }
         } catch (Exception ettUndantag) {
                   
                  }
        
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbOrder;
    private javax.swing.JComboBox<String> cbValjAllaHattar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Label label1;
    private javax.swing.JLabel lblRubrikLaggTIllOrder;
    private javax.swing.JList<String> list1;
    private javax.swing.JList<String> list2;
    // End of variables declaration//GEN-END:variables
}
